#!/usr/bin/env python3
import argparse
import sys
import os
import re
import struct


def parse_file(path: str):
    # reading binary from file
    with open(path, "rb") as f:
        raw = f.read()

    # if first two bytes aren't BM - BMP header indication
    if raw[:2] != b"BM":
        raise ValueError("Not a BMP file")

    # unpacking data from header offset
    pixel_offset = struct.unpack_from("<I", raw, 10)[0]

    # DIB header
    dib_size = struct.unpack_from("<I", raw, 14)[0]

    # if header is too old
    if dib_size < 40:
        raise ValueError("unsupported dib header size")

    width = struct.unpack_from("<i", raw, 18)[0]
    height = struct.unpack_from("<i", raw, 22)[0]
    planes = struct.unpack_from("<H", raw, 26)[0]
    bpp = struct.unpack_from("<H", raw, 28)[0]
    compression = struct.unpack_from("<I", raw, 30)[0]

    # checking if BMP is monochrome
    if bpp != 1:
        raise ValueError(f"expected 1bpp BMP, got {bpp}")

    if compression != 0:
        raise ValueError("compression BMPs are not supported")

    if planes != 1:
        raise ValueError(f"expected 1 colour plane, got {planes}")

    # if the height is negative, then the bitmap is top down
    top_down = height < 0
    height = abs(height)

    # total length of row
    row_stride = ((width + 31) // 32) * 4

    # slicing off the padding
    pixel_data = raw[pixel_offset:]

    rows = []

    for r in range(height):
        # flipping the rows upside down for top to bottom filling
        # top down                      bottom up
        bmp_row_index = r if top_down else (height - 1 - r)
        row_start = bmp_row_index * row_stride
        # slicing the current row between the start and end
        # this still includes the up to 4 bytes of padding at the end
        row_bytes = pixel_data[row_start : row_start + row_stride]
        rows.append(row_bytes)

    output_bits = []

    # converting pixels to bytes
    bytes_per_row = (width + 7) // 8
    leftover = width % 8

    # converting byte array to an array of bits
    for row in rows:
        for byte_index in range(bytes_per_row):
            b = row[byte_index]
            if byte_index == bytes_per_row - 1 and leftover != 0:
                bits = [(b >> i) & 1 for i in range(leftover - 1, -1, -1)]
            else:
                bits = [(b >> i) & 1 for i in range(7, -1, -1)]
            output_bits.extend(bits)

    # debug print
    for y in range(height):
        for x in range(width):
            print(output_bits[(y * width) + x], end="")
        print("")

    # compressing byte array to extreme RLE
    # FORMAT:
    #     - Sequence begins with number of OFF bits in a row
    #     - Then alternates between contiguous ON and OFF bits in a row in this form:
    #     - OFF, ON, OFF, ON
    #     - example:
    #         7, 9, 3, 4, 1
    #         represents 7 off pixels, 9 on pixels, 3 off pixels etc
    #
    #         0, 4, 8, 2
    #         represents 4 on pixels, 8 off pixels, 2 on pixels
    # - IF there is more than 255 of the same pixel in a row,
    # - put 255, 0, then continue with the rest of the number (n - 255)
    #
    # - 0, 600, 3 becomes
    # - 0, 255, 0, 255, 0, 90, 3

    compressed_bits = []

    if output_bits[0] == 1:
        compressed_bits.append(0)

    count = 1

    for bit_index in range(len(output_bits) - 1):
        if output_bits[bit_index] == output_bits[bit_index + 1]:
            if count == 255:
                compressed_bits.append(255)
                compressed_bits.append(0)
                count = 1
            else:
                count += 1
        else:
            compressed_bits.append(count)
            count = 1
    compressed_bits.append(count)

    # debug print
    print("")
    print(compressed_bits)
    print("")

    return width, height, compressed_bits


def sanitise_name(name: str) -> str:
    """Turn a filename into a valid C identifier."""

    name = os.path.splitext(os.path.basename(name))[0]
    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if name and name[0].isdigit():
        name = "_" + name
    return name


def generate_header(data: list, var_name: str, width: int, height: int) -> None:
    guard = f"{var_name.upper()}_H"

    bytes_per_row = (width + 7) // 8
    total_bytes = len(data)

    lines = []
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("/* Auto-generated by BMP_parser.py")
    lines.append(f" * Image : {var_name}")
    lines.append(f" * Size  : {width} x {height} pixels")
    lines.append(
        f" * Layout: {bytes_per_row} byte(s)/row x {height} rows = {total_bytes} bytes total"
    )
    lines.append(" * Pixel 0,0 is top-left.")
    lines.append(" */")
    lines.append("")
    lines.append(f"#define {var_name.upper()}_WIDTH  {width}U")
    lines.append(f"#define {var_name.upper()}_HEIGHT {height}U")
    lines.append("")
    lines.append(f"static const uint8_t {var_name}[{len(data)}U] = {{")
    for value in data:
        hex_str = f"0x{value:02X}"
        lines.append(f"{hex_str},")
    lines.append("};")
    lines.append("")
    lines.append(f"#endif /* {guard} */")
    lines.append("")

    return "\n".join(lines)


def main():
    # getting arguments from cli
    parser = argparse.ArgumentParser()
    os.path
    parser.add_argument("input")
    args = parser.parse_args()
    # checking if file exists
    if not os.path.isfile(args.input):
        print(f"ERROR: File not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    try:
        width, height, data = parse_file(args.input)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    output_path = os.path.splitext(args.input)[0] + ".h"

    var_name = sanitise_name(args.input)
    header = generate_header(data, var_name, width, height)

    with open(output_path, "w") as f:
        f.write(header)

    print(
        f"Successfully compressed bmp to c array. Header file is located in {output_path}"
    )


if __name__ == "__main__":
    main()
