#ifndef FILE_064_OBJNUM_099_24X25_10_28_23_H
#define FILE_064_OBJNUM_099_24X25_10_28_23_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_064_ObjNum_099_24x25_10_28_23
 * Size  : 8 x 12 pixels
 * Layout: 1 byte(s)/row x 12 rows = 1 bytes total
 * Pixel 0,0 is top-left.
 */

static const Image_t File_064_ObjNum_099_24x25_10_28_23 = {
     .width = 8,
     .height = 12,
     .size = 1,
     .data = File_064_ObjNum_099_24x25_10_28_23_DATA
};

static const uint8_t File_064_ObjNum_099_24x25_10_28_23_DATA[1U] = {
     0x60,  /* 96 	*/
};

#endif /* FILE_064_OBJNUM_099_24X25_10_28_23_H */
