#ifndef FILE_062_OBJNUM_097_240X16_10_27_23_H
#define FILE_062_OBJNUM_097_240X16_10_27_23_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_062_ObjNum_097_240x16_10_27_23
 * Size  : 240 x 16 pixels
 * Layout: 30 byte(s)/row x 16 rows = 31 bytes total
 * Pixel 0,0 is top-left.
 */

static const Image_t File_062_ObjNum_097_240x16_10_27_23 = {
     .width = 240,
     .height = 16,
     .size = 31,
     .data = File_062_ObjNum_097_240x16_10_27_23_DATA
};

static const uint8_t File_062_ObjNum_097_240x16_10_27_23_DATA[31U] = {
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0x0F,  /* 15 	*/
};

#endif /* FILE_062_OBJNUM_097_240X16_10_27_23_H */
