#ifndef FILE_074_OBJNUM_138_24X57_10_27_2023_H
#define FILE_074_OBJNUM_138_24X57_10_27_2023_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_074_ObjNum_138_24x57_10_27_2023
 * Size  : 24 x 57 pixels
 * Layout: 3 byte(s)/row x 57 rows = 11 bytes total
 * Pixel 0,0 is top-left.
 */

static const Image_t File_074_ObjNum_138_24x57_10_27_2023 = {
     .width = 24,
     .height = 57,
     .size = 11,
     .data = File_074_ObjNum_138_24x57_10_27_2023_DATA
};

static const uint8_t File_074_ObjNum_138_24x57_10_27_2023_DATA[11U] = {
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0x5D,  /* 93 	*/
};

#endif /* FILE_074_OBJNUM_138_24X57_10_27_2023_H */
