#ifndef FILE_052_OBJNUM_057_72X12_08_30_23_H
#define FILE_052_OBJNUM_057_72X12_08_30_23_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_052_ObjNum_057_72x12_08_30_23
 * Size  : 72 x 12 pixels
 * Layout: 9 byte(s)/row x 12 rows = 29 bytes total
 * Pixel 0,0 is top-left.
 */

static const Image_t File_052_ObjNum_057_72x12_08_30_23 = {
     .width = 72,
     .height = 12,
     .size = 29,
     .data = File_052_ObjNum_057_72x12_08_30_23_DATA
};

static const uint8_t File_052_ObjNum_057_72x12_08_30_23_DATA[29U] = {
     0x49,  /* 73 	*/
     0x45,  /* 69 	*/
     0x03,  /* 3 	*/
     0x45,  /* 69 	*/
     0x03,  /* 3 	*/
     0x06,  /* 6 	*/
     0x1A,  /* 26 	*/
     0x06,  /* 6 	*/
     0x19,  /* 25 	*/
     0x06,  /* 6 	*/
     0x03,  /* 3 	*/
     0x06,  /* 6 	*/
     0x1A,  /* 26 	*/
     0x06,  /* 6 	*/
     0x19,  /* 25 	*/
     0x06,  /* 6 	*/
     0x03,  /* 3 	*/
     0x06,  /* 6 	*/
     0x1A,  /* 26 	*/
     0x06,  /* 6 	*/
     0x19,  /* 25 	*/
     0x06,  /* 6 	*/
     0x03,  /* 3 	*/
     0x45,  /* 69 	*/
     0x03,  /* 3 	*/
     0x45,  /* 69 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0x23,  /* 35 	*/
};

#endif /* FILE_052_OBJNUM_057_72X12_08_30_23_H */
