#ifndef FILE_063_OBJNUM_098_88X13_08_30_23_H
#define FILE_063_OBJNUM_098_88X13_08_30_23_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_063_ObjNum_098_88x13_08_30_23
 * Size  : 88 x 13 pixels
 * Layout: 11 byte(s)/row x 13 rows = 19 bytes total
 * Pixel 0,0 is top-left.
 */

static const Image_t File_063_ObjNum_098_88x13_08_30_23 = {
     .width = 88,
     .height = 13,
     .size = 19,
     .data = File_063_ObjNum_098_88x13_08_30_23_DATA
};

static const uint8_t File_063_ObjNum_098_88x13_08_30_23_DATA[19U] = {
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0x0E,  /* 14 	*/
     0x51,  /* 81 	*/
     0x07,  /* 7 	*/
     0x51,  /* 81 	*/
     0x07,  /* 7 	*/
     0x51,  /* 81 	*/
     0x07,  /* 7 	*/
     0x51,  /* 81 	*/
     0x07,  /* 7 	*/
     0x51,  /* 81 	*/
     0x07,  /* 7 	*/
     0x51,  /* 81 	*/
     0x07,  /* 7 	*/
     0x51,  /* 81 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0x0B,  /* 11 	*/
};

#endif /* FILE_063_OBJNUM_098_88X13_08_30_23_H */
