#ifndef FILE_053_OBJNUM_077_24X12_10_27_23_H
#define FILE_053_OBJNUM_077_24X12_10_27_23_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_053_ObjNum_077_24x12_10_27_23
 * Size  : 24 x 12 pixels
 * Layout: 3 byte(s)/row x 12 rows = 23 bytes total
 * Pixel 0,0 is top-left.
 */

static const Image_t File_053_ObjNum_077_24x12_10_27_23 = {
     .width = 24,
     .height = 12,
     .size = 23,
     .data = File_053_ObjNum_077_24x12_10_27_23_DATA
};

static const uint8_t File_053_ObjNum_077_24x12_10_27_23_DATA[23U] = {
     0x24,  /* 36 	*/
     0x02,  /* 2 	*/
     0x16,  /* 22 	*/
     0x03,  /* 3 	*/
     0x15,  /* 21 	*/
     0x04,  /* 4 	*/
     0x0C,  /* 12 	*/
     0x0D,  /* 13 	*/
     0x0B,  /* 11 	*/
     0x0E,  /* 14 	*/
     0x0A,  /* 10 	*/
     0x0F,  /* 15 	*/
     0x09,  /* 9 	*/
     0x0E,  /* 14 	*/
     0x0A,  /* 10 	*/
     0x0D,  /* 13 	*/
     0x13,  /* 19 	*/
     0x04,  /* 4 	*/
     0x14,  /* 20 	*/
     0x03,  /* 3 	*/
     0x15,  /* 21 	*/
     0x02,  /* 2 	*/
     0x0A,  /* 10 	*/
};

#endif /* FILE_053_OBJNUM_077_24X12_10_27_23_H */
