#ifndef FILE_065_OBJNUM_104_8X12_11_28_23_H
#define FILE_065_OBJNUM_104_8X12_11_28_23_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_065_ObjNum_104_8x12_11_28_23
 * Size  : 8 x 12 pixels
 * Layout: 1 byte(s)/row x 12 rows = 18 bytes total
 * Pixel 0,0 is top-left.
 */

static const Image_t File_065_ObjNum_104_8x12_11_28_23 = {
     .width = 8,
     .height = 12,
     .size = 18,
     .data = File_065_ObjNum_104_8x12_11_28_23_DATA
};

static const uint8_t File_065_ObjNum_104_8x12_11_28_23_DATA[18U] = {
     0x00,  /* 0 	*/
     0x12,  /* 18 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x04,  /* 4 	*/
     0x12,  /* 18 	*/
};

#endif /* FILE_065_OBJNUM_104_8X12_11_28_23_H */
