#ifndef FILE_071_OBJNUM_134_88X75_10_27_23_H
#define FILE_071_OBJNUM_134_88X75_10_27_23_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_071_ObjNum_134_88x75_10_27_23
 * Size  : 88 x 75 pixels
 * Layout: 11 byte(s)/row x 75 rows = 51 bytes total
 * Pixel 0,0 is top-left.
 */

static const Image_t File_071_ObjNum_134_88x75_10_27_23 = {
     .width = 88,
     .height = 75,
     .size = 51,
     .data = File_071_ObjNum_134_88x75_10_27_23_DATA
};

static const uint8_t File_071_ObjNum_134_88x75_10_27_23_DATA[51U] = {
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xE1,  /* 225 	*/
};

#endif /* FILE_071_OBJNUM_134_88X75_10_27_23_H */
