#ifndef FILE_054_OBJNUM_087_24X102_10_27_23_H
#define FILE_054_OBJNUM_087_24X102_10_27_23_H

#include <stdint.h>

/* Auto-generated by BMP_parser.py
 * Image : File_054_ObjNum_087_24x102_10_27_23
 * Size  : 24 x 102 pixels
 * Layout: 3 byte(s)/row x 102 rows = 19 bytes total
 * Pixel 0,0 is top-left.
 */

static const Image_t File_054_ObjNum_087_24x102_10_27_23 = {
     .width = 24,
     .height = 102,
     .size = 19,
     .data = File_054_ObjNum_087_24x102_10_27_23_DATA
};

static const uint8_t File_054_ObjNum_087_24x102_10_27_23_DATA[19U] = {
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0xFF,  /* 255 	*/
     0x00,  /* 0 	*/
     0x99,  /* 153 	*/
};

#endif /* FILE_054_OBJNUM_087_24X102_10_27_23_H */
